services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdk
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_H2_CONSOLE_PATH: /h2-console
    depends_on:
      - h2-db
    entrypoint: ["wait-for-it", "mysql:3306", "--", "java", "-jar", "app.jar"]

  h2-db:
    image: oscarfonts/h2
    ports:
     - "1521:1521"
    environment:
      H2_OPTIONS: '-ifNotExists'